[package]
name = "nimbus"
version = "0.1.0"
edition = "2021"

[dependencies]
dtp = { path = "../dtp/" }
fs = { path = "../fs/" }
rw = { path = "../rw/" }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
dirs = "5.0"
